language: python
matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8
    - python: 3.5
      env: NUMPY=1.8

before_install:
    - travis_retry wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
    - chmod +x miniconda.sh
    - bash miniconda.sh -b -p $HOME/miniconda
    - export PATH=/home/travis/miniconda/bin:$PATH
    - conda update --yes conda
    - sudo apt-get -qq update
    - sudo apt-get install -y nodejs npm
install:
    - conda create --yes -n test python=$TRAVIS_PYTHON_VERSION
    - source activate test
    - conda install --yes numpy=$NUMPY
    - pip install setuptools
    - npm install -g eclint
    - pip install -r requirements.txt
script:
    - flake8
    - eclint check */*.py
    - "sudo sh ./.travis/run_test.sh"
