language: python

matrix:
  include:
    - python: 2.7
    - python: 3.5

install:
    - "sudo pip install -r requirements.txt"

script:
    - "python -m flake8 ."
    - "sudo sh ./.travis/run_test.sh"
