language: python
matrix:
  include:
    - python: 2.7
    - python: 3.5

before_install:
    - sudo apt-get -qq update
    - sudo apt-get install -y nodejs npm
install:
    - npm install -g eclint
    - pip install -r requirements.txt

script:
    - flake8
    - eclint check */*.py
    - "sudo sh ./.travis/run_test.sh"
