language: python
python:
  - '2.7'
  - '3.5'
matrix:
  include:
    - python: 2.7
      env: NUMPY=1.8 SCIPY=0.13
    - python: 3.5
      env: NUMPY=1.8 SCIPY=0.13

before_script:
  - wget http://repo.continuum.io/miniconda/Miniconda-3.8.3-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda install --yes numpy=1.8
  - sudo apt-get -qq update
  - sudo apt-get install -y nodejs npm
install:
  - npm install -g eclint
  - pip install -r requirements.txt
script:
  - flake8
  - eclint check */*.py
  - "sudo sh ./.travis/run_test.sh"
